server:
  port: ${env.port:5022}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${env.db.host:127.0.0.1}:${env.db.port:3306}/${env.db.database:shopdata}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: ${env.db.username:root}
    password: ${env.db.password:123456}
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      filters: config
#      connection-properties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=3000;config.decrypt=${env.db.encrypted:false};config.decrypt.key=${env.db.public-key:}